### ISSUE TITLE
Notification / Training Resources

### ISSUE THREAD

**Issue by hexylena** [usegalaxy-eu/tiaas-group-join#1]
Some ideas after answering a tiaas mail:

- it would be nice that users could see which trainings they are in
- that they get some sort of message in galaxy confirming it (since people have complained before that there is not enough notification.)
- And that administrators could attach resources to trainings and have them prominently available.

would this be useful? Or is it sufficient to say "now click this link to a shared history from the slides"

We could do fancier things too, automatically importing a specific history + switching the user to that history?

cc @bgruening @bebatut @shiltemann and I guess anyone else who uses tiaas? No concrete plans, just some ideas, maybe they sound nice maybe they don't.

**Comment by bgruening** [comment]
All I can provide is the idea of having a real notification system in Galaxy for our users. So we can send notifications to groups, roles, users, all. We could use this for GDPR stuff but also for training.

> "now click this link to a shared history from the slides"

I guess this is sufficient and also part of the learning experience for histories and sharing.

**Comment by hexylena** [comment]
The notification system https://github.com/galaxyproject/galaxy/issues/2324 will happen eventually, we need it. I had not imagined it for training purposes but that could definitely work. We're already using an admin key to create groups, using it to create notifications as well with links to resources is a good idea.

**Comment by shiltemann** [comment]
I agree, some feedback after clicking the join link would be great and probably what users expect. It would also be great for instructors if there was some way to verify that participants successfully joined the group after the fact (e.g. when they complain their jobs are queuing for a long time etc), in my experience there will always be some who forget to click the link before they start.

**Comment by bgruening** [comment]
What we could do and what should be kind of easy to implement is a masthead webhook that only displays a symbol/text when you are in a special training role. This could also be easily checked by the trainer with `make sure you have this symbol in your top-bar ....`

An overview page for the trainer is problematic I guess for GDPR concerns ... I guess.

**Comment by hexylena** [comment]
For now I'm just changing the redirect. Instead of redirecting back to galaxy it redirects to /join-training/about which will show them information.

I'm not sure w/r/t gdpr, we could at least expose usernames since those are already considered public information.

**Comment by hexylena** [comment]
Should be at least somewhat better:

![grafik](https://user-images.githubusercontent.com/458683/44721536-7c47dc00-aaca-11e8-8b29-2bbe02c85058.png)

![grafik](https://user-images.githubusercontent.com/458683/44721543-879b0780-aaca-11e8-8fd6-1d06576b28e7.png)
